import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import World from "./components/World";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Star Wars Movies App",
  description: "Generated by create next app by Sol Olmos",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black">
      <>
      <Navbar></Navbar>
      <div className="scale-50 t-n5"><World></World></div>
      
      </>
      <body className={inter.className}>{children}</body>

    </html>
  );
}
