import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Star Wars Movies App",
  description: "Generated by create next app by Sol Olmos",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
      <Navbar></Navbar>
      </>
      <body className={inter.className}>{children}</body>

    </html>
  );
}
